# Generated by Django 5.0.6 on 2024-06-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
