# Generated by Django 5.0.6 on 2024-06-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
